- setup.py
This lead to an error when trying to upload the package to PyPI
> Missing comma in setup.py

- taf/repository_tool.py
Added a method for specifying expiration dates of metadata files to the Repository class. Specified default expiration intervals based on TUF's default values.
> Added support for setting expiration dates

- .vscode/settings.json
- taf/git.py
Reverts`is_git_repository` changes.
> Revert is_git_repository changes

- setup.py
Allow newer version for cryptography library.
> Fix deps and update version to 0.1.1

- setup.py
- taf/updater/handlers.py
Fix deleting temporary directories on windows
> Fix rmtree for windows

- azure-pipelines.yml
- setup.py
- taf/developer_tool.py
- taf/repository_tool.py
- taf/utils.py
- taf/yubikey.py
- tests/conftest.py
- tests/test_utils.py
- tests/yubikey_utils.py
- Update `oll-tuf` version
- Remove utils function for importing RSA keys and refactor other files
- Fix azure pipeline script (include libusb in wheels)
> Refactor and update dependencies

- taf/auth_repo.py
- taf/git.py
Add helper method to check if given commit has ever been validated.
> Auth validation methods

- .flake8
- .vscode/settings.json
- docs/repo-creation-and-update-util.md
- taf/auth_repo.py
- taf/cli.py
- taf/constants.py
- taf/developer_tool.py
- taf/repositoriesdb.py
- taf/repository_tool.py
- taf/updater/handlers.py
- taf/updater/updater.py
- taf/utils.py
- taf/validation.py
- taf/yubikey.py
- tests/conftest.py
- tests/test_add_targets.py
Closes #54.
Closes #59.
+ some more refactoring.
> General refactoring

- taf/repository_tool.py
Convert path to string when loading keys
> Convert path to string when loading keys

- CHANGELOG.md
- taf/git.py
- Added a method for creating a local branch if a remote branch exists
- Improved check if a branch exists
> Small git module improvements

- CHANGELOG.md
- setup.py
> Update changelog and bump version

- taf/git.py
> Allow custom sorting of git branches

- CHANGELOG.md
- setup.py
- Bump version
- Update CHANGELOG
> Release v0.2.0

- CHANGELOG.md
- taf/git.py
- Updated `list_commits` by allowing branch to be passed in
- Added `list_commit_shas` which returns a list of all commits shas on the specified branch
- Added `set_remote_url` which allows us to change url of the specified remote
> Git updates - updated list_commits and added set_remote_url method

- CHANGELOG.md
- setup.py
- taf/auth_repo.py
- taf/developer_tool.py
- taf/git.py
- taf/log.py
- taf/repositoriesdb.py
- taf/settings.py
- taf/updater/handlers.py
- taf/updater/updater.py
- taf/utils.py
Use loguru library for logging. Enabling/disabling console and/or file logging fixed.
> Logging rework

- CHANGELOG.md
- taf/cli.py
- taf/developer_tool.py
- taf/keystore.py
- taf/repository_tool.py
- taf/utils.py
Closes #85.
- Fix `get_signable_metadata` method
> Update expiration date CLI fix

- CHANGELOG.md
- docs/repo-creation-and-update-util.md
- setup.py
> Release v0.2.1

- CHANGELOG.md
- taf/repository_tool.py
Added a method which deletes all target files which are not specified in `targets.json`
> Added a method which deletes target files not specified in targets.json

- CHANGELOG.md
- setup.py
> Release v0.2.2

- CHANGELOG.md
- taf/developer_tool.py
- taf/exceptions.py
- taf/git.py
- taf/keystore.py
- taf/repository_tool.py
- taf/tests/test_repository_tool.py
- taf/yubikey.py
Added support for delegated targets roles
- Support creation of delegations when creating a new repository
- Implemented updated of metadata files corresponding to delegated roles
- Refactored and updated metadata signing - each role can be signed with multiple keys, which can be loaded from disk or kept on Yubikeys
Closes #52
> Support delegated targets roles

- taf/developer_tool.py
- taf/keystore.py
- taf/repository_tool.py
Fix/update methods for updating expiration times of snapshot and timestamp metadata files.
Support updating delegated metadata files.
> Add an option to update any role's expiration time

- taf/__init__.py
- taf/developer_tool.py
- taf/repository_tool.py
- reset roledb when updating targets
- option to reload tuf repository
> Target role fixes

- CHANGELOG.md
- taf/auth_repo.py
- taf/exceptions.py
- taf/git.py
- taf/log.py
- taf/repositoriesdb.py
- taf/utils.py
- added `*args` and `**kwargs` arguments to repositories, so that additional data can be specified when instantiating them
- added a check if at least one repository was loaded given an authentication repository
- temporarily added `clone_or_pull` method - we need it at the moment, but I think that we should remove it once that is no longer the case
> Repositories enhancements

- CHANGELOG.md
- setup.py
> Release v0.3.0

- CHANGELOG.md
- taf/repositoriesdb.py
A small repositoriesdb fix - exit if auth repo has not commits
> A small repositoriesdb fix

- taf/git.py
> clone_or_pull fix

- taf/developer_tool.py
> A small create repo fix

- taf/repository_tool.py
A small update role metadata fix
> A small update role metadata fix

- CHANGELOG.md
- setup.py
> Release v0.3.1

- CHANGELOG.md
- taf/developer_tool.py
- taf/repository_tool.py
- taf/tools/metadata/__init__.py
- taf/tools/repo/__init__.py
- taf/utils.py
`keys_description.json` is now expected to contain a "roles" dictionary and a "keystore" location (though both are optional), like this:
```
{
"roles": {
"root": {
"number": 2,
"length": 2048,
"threshold": 2
},
"targets": {
"length": 2048
},
"snapshot": {},
"timestamp": {}
},
"keystore": "keystore_path"
}
```
Update snapshot and timestamp when adding a new signing key
Create repository improvements
Closes #108 
Closes #95 
> Create repository improvements and some fixes

- CHANGELOG.md
- taf/developer_tool.py
- taf/repository_tool.py
- taf/tools/targets/__init__.py
- When creating a new repository, if there are existing target files which should be registered, they need to be normalized.
- Some small loading keys fixes
Closes #81 
> Create repository and sign targets fixes

- CHANGELOG.md
- taf/__init__.py
- taf/developer_tool.py
- taf/keystore.py
- taf/log.py
- taf/repository_tool.py
> Various bug fixes

- CHANGELOG.md
- taf/git.py
- Made clone more flexible - added an option to pass in additional arguments. Useful if e.g. we need a shallow clone
- Fixed `synced_with_remote`. We used to only check if local and remote tracking branch have the same top commit. This does not work if the remote tracking branched is not up to date.
> Git updates

- CHANGELOG.md
- taf/git.py
- taf/repositoriesdb.py
Changed factory function that allows us to update only certain target repositories.
> Updater: Partial repo factory

- CHANGELOG.md
- taf/developer_tool.py
- taf/repository_tool.py
> Updated `add_signing_key` so that it supports adding keys to delegated roles

- CHANGELOG.md
- taf/git.py
- taf/tests/test_yubikey.py
- taf/tests/yubikey_utils.py
- `git.py` create orphan branch
- fix import errors inside tests
> Oolaaf integration changes

- CHANGELOG.md
- setup.py
> Release v0.4.0

- CHANGELOG.md
- taf/auth_repo.py
- taf/exceptions.py
- taf/git.py
- taf/repositoriesdb.py
- taf/updater/handlers.py
- taf/updater/updater.py
- taf/validation.py
- Standardize log and error message
- Added a `GitError` exception which is raised instead of reraising `CalledProcessError` error
- Went through git methods and updated logging
- Raise a custom error if a repository cannot be instantiated
- Small updater improvements - call cleanup even if inistialization fails (and not just if update fails)
> Error handling and logging improvements

- CHANGELOG.md
- setup.py
- taf/keystore.py
> Release v0.4.1

- CHANGELOG.md
- setup.py
> Release v0.5.0

- CHANGELOG.md
- taf/developer_tool.py
- taf/repository_tool.py
- taf/tests/test_updater.py
- taf/tools/metadata/__init__.py
- Simplified the code and also makes it possible to load signing keys from keystore files.
- Fixed a bug with adding new signing keys of delegated roles
> Use _load_signing_keys in add_signing_key

- CHANGELOG.md
- docs/quickstart.md
- docs/repo-creation-and-update-util.md
- docs/testing_notes.md
- taf/tools/repo/__init__.py
- taf/tools/targets/__init__.py
Updated out of date documentation
> Documentation updates

- CHANGELOG.md
- setup.py
> Release v0.5.1

- CHANGELOG.md
- taf/git.py
- taf/log.py
- taf/updater/updater.py
When checking if a branch exists, if the repository has remote, check if
the the branch exists in the remote repository - instead of only checking
if there is a remote tracking branch.
Added a method for removing remote tracking branches
> Update check if branch exists and method for deleting remote tracking branches

- CHANGELOG.md
- setup.py
> Release v0.5.2

- CHANGELOG.md
- taf/git.py
- taf/validation.py
- Added git method for getting the first commit on a branch
- Minor capstone validation update
> A new git method and check capstone update

- CHANGELOG.md
- setup.py
> Release 0.6.0

- CHANGELOG.md
- taf/auth_repo.py
- taf/git.py
- taf/updater/updater.py
- taf/utils.py
Added an option to get binary file from git (skips encoding) while running the process.
> Get binary file with git show

- CHANGELOG.md
- setup.py
> Release v0.6.1

- README.md
- azure-pipelines.yml
- docs/devops.md
- Build wheels for python 3.8
- Add documentation for Azure devops script
> Extend build script with python3.8 and add documentation

- taf/__init__.py
Fix loading DLLs for python 3.8 on Windows.
> Use add_dll_directory instead of extending PATH variable

- CHANGELOG.md
- taf/git.py
- taf/repositoriesdb.py
- taf/tests/test_repositoriesdb.py
- taf/tests/test_repositoriesdb_mirrors.py
- taf/tests/yubikey_utils.py
- Updated some git methods so that it is checked if the returned value is not `None` before calling `strip`
- Store authentication repo's path as key in `repositoriesdb` instead of its name. This ensures that repositories will be loaded again if there is a repo of the same name at a different location
- Minor YubiKey mock fixes
> Git and yubikey fixes

- CHANGELOG.md
- taf/log.py
Added a function for fully disabling `tuf` and `securesystemslib` file logging
> Disable tuf file logging

- CHANGELOG.md
- setup.py
> Release v0.7.0

- CHANGELOG.md
- taf/git.py
In the new version of git, a prefix is added to names of branches checked out
in some other worktree.
> A small update made to the method which finds branches containing a commit

- CHANGELOG.md
- setup.py
> Release v0.7.1

- CHANGELOG.md
- setup.py
> Release 0.7.2

- CHANGELOG.md
- taf/tools/yubikey/__init__.py
> Added a command for checking validity of  inserted Yubikey's pin

- .pre-commit-config.yaml
- CHANGELOG.md
- taf/auth_repo.py
- taf/repository_tool.py
Raise keystore error when key not found in keystore directory. Added is_test_repo property
> Raise keystore error when key not found in keystore directory. Added is_test_repo property

- CHANGELOG.md
- setup.py
> Release 0.8.1

- .github/workflows/ci.yml
> Transition from TravisCI to Github Actions

- CHANGELOG.md
- docs/developers/testing_notes.md
- docs/quickstart.md
- docs/repo-creation-and-update-util.md
- docs/setting-up-new-library.md
- setup.py
Update click requirement and the documentation. Release 0.10.0
> Update click to 7.1

- CHANGELOG.md
- taf/hosts.py
> Do not raise an error if hosts file is missing, only if it is invalid

- CHANGELOG.md
- setup.py
> Release 0.10.1

- CHANGELOG.md
- MANIFEST.in
- setup.py
> Exclude test data from wheels

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.py
- taf/tests/yubikey_utils.py
- taf/yubikey.py
Closes: #186 
Based on issue #186, it is necessary to migrate `ykman v3.0.0` to `v4.0.7`
* Refactor `connection_to_device` to comply with `ykman v4.0.7`
* Replace `PivController` with `PivSession`
* Refactor `taf yubikey setup-test-key` command and add `cryptography` imports necessary to construct a self-signed certificate
* Update mocks and tests according to previous refactors
> Transition to Yubikey Manager v4.0.7

- CHANGELOG.md
- setup.py
> Release 0.13.2

- CHANGELOG.md
- setup.py
- taf/auth_repo.py
Trim text read from the last_validated_commit file
> Relase 0.13.4

- CHANGELOG.md
- setup.py
> Release 0.14.0

- CHANGELOG.md
- taf/updater/handlers.py
Return an empty list of targets if the targets folder does not exist
> Return an empty list of targets if the targets folder does not exist

- CHANGELOG.md
- setup.py
- taf/auth_repo.py
- taf/hosts.py
- taf/repositoriesdb.py
- taf/tests/conftest.py
- taf/tests/data/handler_inputs/invalid/host/missing_required.json
- taf/tests/data/handler_inputs/invalid/host/wrong_type.json
- taf/tests/data/handler_inputs/invalid/repo/additional_property.json
- taf/tests/data/handler_inputs/invalid/repo/missing_required.json
- taf/tests/data/handler_inputs/invalid/repo/missing_required_inner.json
- taf/tests/data/handler_inputs/invalid/repo/wrong_type.json
- taf/tests/data/handler_inputs/invalid/update/array_instead_of_object.json
- taf/tests/data/handler_inputs/invalid/update/required_field_missing.json
- taf/tests/data/handler_inputs/valid/host/host.json
- taf/tests/data/handler_inputs/valid/repo/failed_repo.json
- taf/tests/data/handler_inputs/valid/repo/succeeded_repo.json
- taf/tests/data/handler_inputs/valid/repo/succeeded_unauthenticated_commits_repo.json
- taf/tests/data/handler_inputs/valid/repo/succeeded_with_new_commits_repo.json
- taf/tests/data/handler_inputs/valid/repo/unchanged_repo.json
- taf/tests/data/handler_inputs/valid/update/update.json
- taf/tests/data/types/update/invalid/wrong_nested_field.json
- taf/tests/data/types/update/valid/update_all_fields.json
- taf/tests/data/types/update/valid/update_no_hosts.json
- taf/tests/test_schemas.py
- taf/tests/test_types.py
- taf/updater/lifecycle_handlers.py
- taf/updater/schemas.py
- taf/updater/types/update.py
- taf/updater/updater.py
Closes #198 
* Implemented `update` handler which is the final part of the pipeline lifecycle. The update handler aggregates all information returned by `host` and `repo` handler. The result is a JSON with nested information pointing to updated repositories, hosts and dependencies of a root repository which called the updater. 
* Initial work on mapping dict data to class types using `attrs`. 
* Added unit tests for type class structuring and `update` json schema validation
To update `openlawlibrary/law`, run `taf repo update https://github.com/oll-test-repos/openlawlibrary-law.git PATH_TO_LAW --default-branch master --scripts-root-dir YOUR LOCATION`
> Pull pipeline - update handler

- CHANGELOG.md
- setup.py
> Release 0.15.0

- azure-pipelines.yml
Replace deprecated windows image with the newest one
Closes #221
> Replace deprecated windows image with the newest one

- CHANGELOG.md
- taf/repositoriesdb.py
- taf/updater/updater.py
QoL and bug fixes that popped up when testing the framework.
* Default branch for targets was `main` and extracted from target_repos default branch even though `default_branch` flag was overriden to be `master` for example.
* commits[1::] kept failing when there exists a repo with only a root commit.
> Branch and target fixes

- CHANGELOG.md
- setup.py
- taf/git.py
> Release 0.16.0

- CHANGELOG.md
- docs/repo-creation-and-update-util.md
- docs/setting-up-new-library.md
- docs/updater/specification.md
Introduced a `info.json` metadata file. It resides in protected/ folder that in the future should be protected with a quorum of keys. Add docs with a general outline
> Update docs with `info.json` 

- CHANGELOG.md
- taf/auth_repo.py
Extend the dictionary which is generated for each target repository and
each of its branches for each auth repo commit with auth commit's data:
```
{
target_repo: {
branch1: [
{"commit": commit1, "custom": {...}, "auth_commit": auth_commit1},
{"commit": commit2, "custom": {...}, "auth_commit": auth_commit2},
{"commit": commit3, "custom": {...}, "auth_commit": auth_commit3}
] ...
}
```
> Add auth commit to sorted_commits_and_branches_per_repositories

- CHANGELOG.md
- setup.py
> Release 0.17.0

- docs/updater/specification.md
Minor typo / fprmatting fixes in the specification.
> Minor typo fixes

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- azure-pipelines.yml
- setup.py
* Since we're transitioning to py310, update `azure-pipelines.yml` to
build on latest python and ubuntu.
Adds support for python 3.10. 
* Updated GitHub Actions script to build on  all newer python versions.
* Update Azure to build on all newer python versions.
* Conditional `pygit2` dependency, either `0.28.2` if py36 or `1.9.*` if >= py3.7.
* Bump bandit to a newer version, old version with py310 raises `click` errors (tries to install `click >= 8.*`). 
> Upgrade to Python 3.10 

- CHANGELOG.md
- setup.py
> Release 0.18.0

- CHANGELOG.md
- setup.py
An error might occur while installing the newest pynacl, so pin it to the one that surely works. Loosen click and loguru dependencies
> build: loosen dependencies and pin pynacl

- CHANGELOG.md
- docs/common-issues.md
Document a solution to a YubiKey communication issue
> docs: Document a solution to a YubiKey communication issue

- CHANGELOG.md
- taf/git.py
remove pygit2 push implementation which does not fully support ssh
> fix: remove pygit2 push implementation which does not fully support ssh

- CHANGELOG.md
- setup.py
> chore: update changelog and bump version to 0.21.0

- CHANGELOG.md
- setup.py
> chore: update changelog - release 0.21.1

- CHANGELOG.md
- setup.py
Release 0.22.0. Please see [CHANGELOG](https://github.com/openlawlibrary/taf/blob/master/CHANGELOG.md) for updates.
> Release 0.22.0

- .pre-commit-config.yaml
- taf/auth_repo.py
- taf/git.py
- taf/repositoriesdb.py
- taf/settings.py
- taf/tests/test_repository.py
- taf/tests/test_updater.py
- taf/tools/repo/__init__.py
- taf/updater/updater.py
> feat: auto-detect default branch

- CHANGELOG.md
- setup.py
> Release 0.23.0

- .github/workflows/ci.yml
- CHANGELOG.md
- taf/git.py
We shouldn't need to fetch the default branch if intention is to clone the repository
> Fix `clone_or_pull`

- CHANGELOG.md
- setup.py
> chore: update changelog - release 0.23.1

- CHANGELOG.md
- taf/git.py
- added a method for adding and removing remotes
- when merging commits, optionally check if a merge conflict occurred
- reraise an error if push fails
> feat: git additions

- CHANGELOG.md
- setup.py
> Release 0.24.0

- CHANGELOG.md
- taf/repositoriesdb.py
- taf/settings.py
- taf/updater/lifecycle_handlers.py
Do not raise an error if there are no scripts corresponding to certain handlers. It should not be mandatory to have any scripts at all. Fix scripts call. Use `sys.executable` instead of `py`
> fix: fix execution of scripts

- LICENSE.md
- LICENSE.txt
- setup.py
Update license, release under agpl
> Update license, release under agpl

- CHANGELOG.md
- setup.py
> Release 0.25.0

- README.md
Fix link to TAF implementation of TUF
> fix: update link to tuf specification

- taf/keys.py
> fix: fix key read error msg when bad file

- CHANGELOG.md
- setup.py
> Release v0.26.0

- taf/api/roles.py
> chore: fix a typo

- CHANGELOG.md
- setup.py
pygls relies on `lsprotocol`, which relies on latest `cattrs`.
> refact: upgrade `cattrs`

- CHANGELOG.md
- taf/api/metadata.py
- taf/api/roles.py
- taf/api/targets.py
- taf/keys.py
- taf/tools/cli/__init__.py
- taf/tools/dependencies/__init__.py
- taf/tools/targets/__init__.py
- Fix error when running commands in case when keystore is not specified
- When entering custom arguments (in case of commands that include definition of custom data - adding target repos and dependencies), show a nicer error message if they are entered incorrectly and convert "true" and "false" to boolean values
- Fix incorrect `repositories.json` path when adding a new target repo
- Update docstrings
- When removing a delegated path, do not update snapshot and timestamp if the delegated path did not exist and targets metadata was not udpated
> Add remove target repo fixes

- CHANGELOG.md
- taf/tests/test_repository.py
A simple PR that adds one missing tests. Everything worked, so there was no need to fix anything
Close #170 
> test: add test for repo initialization when it is directly inside drive's root

- CHANGELOG.md
- setup.py
> Release 0.27.0

- .pre-commit-config.yaml
- CHANGELOG.md
- mypy.ini
- setup.py
- taf/api/keystore.py
- taf/api/metadata.py
- taf/api/repository.py
- taf/api/roles.py
- taf/api/targets.py
- taf/api/yubikey.py
- taf/auth_repo.py
- taf/constants.py
- taf/exceptions.py
- taf/git.py
- taf/keys.py
- taf/keystore.py
- taf/log.py
- taf/models/converter.py
- taf/models/types.py
- taf/models/validators.py
- taf/pygit.py
- taf/repositoriesdb.py
- taf/repository_tool.py
- taf/tests/test_yubikey/test_yubikey.py
- taf/tools/cli/taf.py
- taf/tools/repo/__init__.py
- taf/updater/handlers.py
- taf/updater/updater.py
- taf/yubikey.py
- Added mypy pre-commit check. Use version 1.4.1, which is the last version that supports Python 3.7
- Addressed a variety of issues that mypy reported, mostly:
- variable of one type being assigned a value of a different type, like when converting a string to a Path instance
- error handling when a variable can be `None`
- incorrect typing clues that were previously added
- rework of roles description models, remove `DelegatedRole`, `TargetsRole` can now contain a list of delegated `TargetsRole` objects
- Some generation of keys fixes, in cases when the keystore should have a password or when it should be printed to console
- Added additional type hints
Closes #287 
Did no test cli, it's possible that this will introduce some regressions, but since the next big chunk of work will add api …
> Set up mypy and fix the issues it reported

- CHANGELOG.md
- README.md
- setup.py
> chore: release 0.28.0

- CHANGELOG.md
- setup.py
> Release 0.29.0

- CHANGELOG.md
- taf/tests/test_updater/test_repo_update/test_updater.py
- taf/updater/lifecycle_handlers.py
- taf/updater/types/update.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
- Fix `_update_named_repository` call
- Remove an unused function
- Fix update of referenced authentication repositories in case when the parent repository exists and the child does not (caused by the recent separation of clone and update functionalities)
- Improve error reporting
> Improve error messages and minor fixes

- CHANGELOG.md
- setup.py
> Release 0.29.1

- CHANGELOG.md
- setup.py
- taf/git.py
> fix(git): clone repo if `pygit` can't be instantiated

- CHANGELOG.md
- setup.py
- taf/tests/test_updater/test_repo_update/test_updater.py
- taf/updater/updater_pipeline.py
Temporary measure until we start fully supporting validation on local disk
> fix(updater): set local disk validate during strict mode

- CHANGELOG.md
- taf/api/utils/_roles.py
- taf/repository_tool.py
- taf/tests/test_repository_tool/test_repository_tool.py
- taf/utils.py
Reimplemented functions get_file_details and load_json_file from securesystemslib version 0.25 in utils.py.
Closes #417 
> fix: reimplemented securesystemslib util functions get_file_details and load_json_file

- CHANGELOG.md
- taf/api/roles.py
- taf/tools/roles/__init__.py
…cation repository
A command that lists all roles in an authentication repository.
Closes #400
> feat: new function taf roles list that lists all roles in an authentication repository

- CHANGELOG.md
- taf/tools/dependencies/__init__.py
- taf/tools/keystore/__init__.py
- taf/tools/metadata/__init__.py
- taf/tools/roles/__init__.py
- taf/tools/targets/__init__.py
- taf/tools/yubikey/__init__.py
Refactors CLI in a better format (avoid renaming functions by adding "_" to their names"
> refact: refact cli

- .flake8
- .github/workflows/ci.yml
- CHANGELOG.md
- azure-pipelines.yml
- setup.py
- taf/tools/yubikey/__init__.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
**Addresses Issue**: #379
fixes: #379
**Summary of Changes**:
1. **Dependency Updates**:
- Updated dependency versions to support Python 3.11 and Python 3.12.
- The build process will now consider the Python version to select the appropriate libraries.
- **Click Library**: Updated to version 8.*.*.
- **pygit2 Library**:
- For Python 3.8, updated to version 1.10.1.
- For Python 3.9 and 3.10, updated to version 1.13.3.
- For Python 3.11 and 3.12, updated to version 1.14.1.
2. **Build and Workflow Updates**:
- Updated GitHub workflows to accommodate the new Python versions and dependencies.
- Updated Azure Pipelines configuration for compatibility with the updated dependencies and Python versions.
3. **Documentation**:
- Updated `CHANGELOG.md` to reflect these changes.
[changelog]: …
> Update to support Python 3.11 and 3.12

- CHANGELOG.md
- setup.py
- taf/yubikey.py
fixes: #410 
- Updated code to support Yubikey Manager 5.1.x 
- Changes are made to remove deprecated modules and functions and use newer ones.
- Dropped support for Yubikey Manager 4.x
> Support Yubikey Manager 5.1.x

- CHANGELOG.md
- setup.py
> Release 0.30.0

- .github/workflows/ci.yml
- CHANGELOG.md
- taf/__init__.py
Added a new Github action to build standalone executables of TAF. Resolves issue #367 
> feat: new github action to create standalone executable of TAF

- CHANGELOG.md
- taf/api/repository.py
- taf/updater/updater_pipeline.py
- taf/utils.py
Added git hook check to updater. Resolves issue #393
> feat: added git hook check for updater

- CHANGELOG.md
- taf/tests/test_updater/test_clone/test_clone_invalid.py
- taf/tests/test_updater/test_clone/test_clone_valid.py
- taf/tests/test_updater/test_update/test_update_valid.py
- taf/tests/test_updater/update_utils.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
Minor formatting and test fixes after the addition of the no-upstream flag
> Minor formatting and test fixes after the addition of the no-upstream flag

- CHANGELOG.md
- taf/api/metadata.py
- taf/api/targets.py
- taf/api/utils/_git.py
Enhanced version of enhanced commit_and_push function. Fix #468 
> feat: enhanced commit_and_push

- CHANGELOG.md
- taf/api/conf.py
- taf/api/keystore.py
- taf/api/utils/_conf.py
- taf/keys.py
- taf/keystore.py
- taf/repository_utils.py
- taf/tools/cli/taf.py
- taf/tools/conf/__init__.py
- taf/tools/dependencies/__init__.py
- taf/tools/keystore/__init__.py
- taf/tools/metadata/__init__.py
- taf/tools/repo/__init__.py
- taf/tools/roles/__init__.py
- taf/tools/targets/__init__.py
- taf/tools/yubikey/__init__.py
- taf/utils.py
Improved usability (TAF finds the repo if current directory has no repo, create a .taf directory to manage keys). 
Fix #461 
> feat: improved usability (TAF finds the repo if current directory has no repo, create a .taf directory to manage keys)

- taf/yubikey.py
> chore: remove duplicate import

- CHANGELOG.md
- taf/auth_repo.py
- taf/constants.py
- taf/updater/updater_pipeline.py
Implemented info.json data loading.
> info.json data loading

- CHANGELOG.md
- taf/<taf.auth_repo.AuthenticationRepository object at 0x1076801d0>/dirty_file.txt
- taf/git.py
- taf/tests/test_updater/conftest.py
- taf/tests/test_updater/test_update/test_update_invalid.py
- taf/tests/test_updater/test_update/test_update_valid.py
- taf/tests/test_updater/update_utils.py
- taf/tools/repo/__init__.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
Added forced updates to the updater. Fix #467.
> feat: added --force to taf repo update

- taf/tools/repo/__init__.py
Removed unnecessary force variable in taf repo clone
> fix: removed unnecessary force variable in taf repo clone

- taf/tools/repo/__init__.py
> chore: fix flake issue

- CHANGELOG.md
- taf/tests/init_data/dependencies.json
- taf/tests/test_updater/conftest.py
- taf/tests/test_updater/test_update_library/conftest.py
- taf/tests/test_updater/test_update_library/test_clone_library_invalid.py
- taf/tests/test_updater/test_update_library/test_update_library_invalid.py
- taf/tests/test_updater/update_utils.py
- taf/updater/updater.py
Fix update repos with dependencies and enable tests
> Fix update repos with dependencies and enable tests

- CHANGELOG.md
- taf/tests/test_updater/conftest.py
- taf/tests/test_updater/test_update/test_update_invalid.py
- taf/tests/test_updater/test_update/test_update_valid.py
- taf/tests/test_updater/test_update/test_validation_and_sync.py
- taf/tests/test_updater/update_utils.py
- taf/updater/updater_pipeline.py
> Out-of-sync test improvements

- taf/updater/updater.py
- taf/updater/updater_pipeline.py
Fixes a minor bug to taf validation we noticed during pairing
> fix: set last validated commit correctly

- CHANGELOG.md
- setup.py
- taf/log.py
- taf/tests/test_updater/test_repo_update/test_updater.py
- taf/tools/repo/__init__.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
This pr contains cherry-picked commits from https://github.com/openlawlibrary/taf/pull/455 pr that are going into the 0.30.2 point release. 
> chore: Release three new flags including `--no-deps`

- CHANGELOG.md
- setup.py
- taf/git.py
- taf/tests/test_repository_tool/conftest.py
- taf/tests/test_repository_tool/test_repository_tool.py
- taf/tests/test_yubikey/conftest.py
- taf/tests/yubikey_utils.py
Reverts openlawlibrary/taf#516
> Revert "Sbojanic/move yubikey utils v2"

- CHANGELOG.md
- taf/updater/lifecycle_handlers.py
- taf/updater/updater.py
- taf/utils.py
Added support for execution of executable files within the scripts directories
This was implemented and tested by @jc12690, but we couldn't merge the PR due to the commit history being severely out-of-sync with master.
I'm fine with merging this in without in-depth testing, since we will need to do more work on the handlers soon and they are not being used atm
Closes #482
> feat: Added support for execution of executable files within the scripts directories

- taf/exceptions.py
- taf/git.py
> fix: raise original error message alongside generic GitError message

- CHANGELOG.md
- setup.py
- taf/git.py
- taf/repositoriesdb.py
- taf/resources/pre-push
- taf/tests/test_repository_tool/conftest.py
- taf/tests/test_repository_tool/test_repository_tool.py
- taf/tests/test_yubikey/conftest.py
- taf/tools/repo/__init__.py
- taf/tools/yubikey/yubikey_utils.py
- taf/updater/updater.py
- taf/updater/updater_pipeline.py
> chore: release 0.31.1

- taf/tools/repo/__init__.py
> fix: add verbosity to clone

- CHANGELOG.md
- setup.py
- taf/api/repository.py
- taf/git.py
- taf/tools/cli/__init__.py
- taf/tools/repo/__init__.py
- taf/updater/updater_pipeline.py
- Two `GitError` instances were being created in an erroneous way (causing str does not have log_prefix errors) 
- When restarting an update, it's necessary to combine fetched with already existing commits, or the repos will never get updated
> Fix Git Errors and Resetting Validation

- taf/git.py
> `get_last_remote_commit` resolve url within method

- CHANGELOG.md
- setup.py
> Release 0.33.0

- CHANGELOG.md
- setup.py
- taf/updater/updater_pipeline.py
> chore: Release `v0.33.2`

- taf/tests/tuf/test_query_repo/test_query_repo.py
> Fix test_sort_roles_targets_for_filenames

- CHANGELOG.md
- setup.py
> chore: release 0.34.0

- CHANGELOG.md
- taf/api/targets.py
- taf/auth_repo.py
- taf/tests/test_api/util.py
- taf/updater/updater_pipeline.py
If `branch` is not specified in target files, default branch was read from auth repo instead of corresponding target repo.
Rename `target_path` to `target_name`.
> Fix wrong default branch assignment

- CHANGELOG.md
- taf/api/api_workflow.py
- taf/tools/cli/__init__.py
- taf/tuf/repository.py
Retain backwards compatibility with the old TAF
> fix: ensure that every target role has a delegations attribute

- CHANGELOG.md
- taf/repositoriesdb.py
Recursively iterate through dependencies and add all auth repos to a list.
> feat: implement get all auth repos

- CHANGELOG.md
- taf/keys.py
- taf/tuf/repository.py
- taf/yubikey/yubikey.py
> fix: fix setting names of keys when not stored in metadata files

- CHANGELOG.md
- taf/tools/cli/__init__.py
- taf/tools/cli/lazy_group.py
- taf/tools/cli/olc.py
- taf/tools/cli/taf.py
> fix: optionally include yubikey cli group

- README.md
This PR adds a section to `README.md` that describes related projects to TAF (in specific, gittuf). This is based on my understanding of the similarities and differences comparing gittuf with TAF. Tried to not write it like an advertisement.
Addresses #598.
> README.md: Add a brief comparison with gittuf

- CHANGELOG.md
- setup.py
This is the first prerelease version of TAF intended to test our integration with taf internally, before rolling it out to everyone.
> chore: prerelease 0.35.0-alpha.1

- CHANGELOG.md
- taf/api/api_workflow.py
- taf/tuf/repository.py
> fix: sort order of roles in `manage_repo_and_signers`

- CHANGELOG.md
- taf/api/api_workflow.py
- taf/keys.py
- Fixes to `key_management` decorator following integration with platform
- Introduce `key_management_context` manager that works as a contextmanager, instead of a decorator. This change lets us be flexible in our codebase without many changes.
> refact: `key_management` fixes

- taf/tools/roles/__init__.py
> chore: fix `taf roles add` docstring

- CHANGELOG.md
- setup.py
- taf/tools/roles/__init__.py
- taf/tuf/keys.py
- Add back `keyid_hash_algorithms` key to `targets.json` metadata key section for legacy purposes
> feat: add `keyid_hash_algorithms` to metadata keys

- CHANGELOG.md
- taf/tools/roles/__init__.py
- taf/yubikey/yubikey.py
> fix: Fix key prompt

- CHANGELOG.md
- taf/api/roles.py
- taf/keys.py
- taf/tools/metadata/__init__.py
- taf/tools/roles/__init__.py
- taf/tools/yubikey/__init__.py
- taf/utils.py
Closes #629
Closes #633 
Closes #631
> refact, fix: various small fixes

- CHANGELOG.md
- taf/api/api_workflow.py
When taf is installed (without yubikey), running taf commands should work.
Closes #640
> chore: fix yk imports

- taf/updater/lifecycle_handlers.py
> fix: move `persistent.json` to `.taf` dir

- CHANGELOG.md
- taf/settings.py
- taf/tools/repo/__init__.py
- taf/updater/lifecycle_handlers.py
- taf/updater/updater.py
> feat: add run-scripts flag to execute lifecycle handler scripts

- CHANGELOG.md
- setup.py
- taf/tests/tuf/test_keys/test_pin_from_env.py
- taf/tools/repo/__init__.py
- taf/yubikey/yubikey.py
- Fix pin lookup
- Add profile to taf repo validate
> fix: minor fixes; prepare for `0.35.0`

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.py
- taf/config.py
- taf/log.py
> fix: Log and import fixes

- taf/tests/test_api/targets/api/test_targets.py
- taf/utils.py
> fix(test): remove windows condition
