taf/GitRepository.py
taf/exceptions.py
taf/repositoriesdb.py

- Raising a nicer error if repositories.json or mirrors.json does not exist or is not valid
- Added the ability to pass in more than one commit when loading repositories
- Finding a deduplicated list of repositories given one or more commits

Some repositoriesdb improvements

---

taf/updater/updater.py
tests/test_updater.py

The update used to fail when a repository which allows unauthenticated commits had no new commits or only commits which are not registered in the authentication repository.
Testing the case when no update is necessary and one of the target repositories allows unauthenticated commits.

Fixed update of repositories which allow unauthenticated commits

---

taf/utils.py
tests/test_utils.py

Because the updater relies on `git show` which seems to strip the new line at the end of the file, this ensures that all new lines are removed when adding targets. 
Closes #38

Remove new lines from the end of files when adding targets

---

taf/cli.py
taf/developer_tool.py
taf/git.py
tests/test_repository.py
tests/test_updater.py

- If the authentication repository is in the same directory as the target directories, it is skipped. This happens both when adding target repos and when generating `repositories.json`
- Using `pathlib` instead of `os`. Support for relative paths
- Setting default `namespace` value. It should be the same as the name of the directory that contains target repositories.
- Validation of repository's urls does not fail if a url is a valid ssh url
- Added tests for validation of urls
Closes #37 
Closes #39 
Closes #44

Generation of target files, repositories.json fixes and support for ssh urls

---

taf/updater/handlers.py
taf/updater/updater.py
taf/utils.py
tests/test_updater.py
tests/test_utils.py

- Update does not fail if last_validated_commit does not exist. It validates the repositories starting from the beginning
- Normalize line endings fix. It is necessary to read and write files as binary.
- Updated tests
Closes #46

Start update from beginning if last validated commit doesn't exist and normalize new lines fix

---

setup.py
taf/developer_tool.py

Pass scheme argument when loading _timestamp_ and _snapshot_ keys.
Depends on https://github.com/openlawlibrary/tuf/pull/11.

Fix pass scheme when loading keys

---

CHANGELOG.md
taf/validation.py

Updated validation in cases when there are more commits on authentication
repository's branch than on corresponding branches of target repositories.
The missing commits used to be populated with `None` values and validation would
only cover unmerged commits of target repositories.
However, there could initially be more commits on the authentication repository. Also, adding `None` values does not verify that those commits which are supposedly merged are valid. So, validation will now take as many commits from target repositories as there are commits on authentication repository's branch and verify that they all belonged to the appropriate branch at one point.
[changelog]: …

Updated validation of branches

---

CHANGELOG.md
docs/testing_notes.md
taf/cli.py
taf/developer_tool.py
taf/exceptions.py
taf/keystore.py
taf/repository_tool.py
taf/utils.py
taf/yubikey.py

- Added new commands for:
- setting up a new yubikey
- exporting a public key from inserted yubikey
- adding a new signing key (currently assumes that all keys are stored on yubikeys)
- Improved creation of repositories:
- check keystore before inserting all of yubikeys
- created standardized yubikey prompt
-  keep retrying to access the yubikey rather than failing out with an exception (can take a few seconds for computer to recognize yubikey after inserted)
-  store pins globallyso don't have to keep typing password.
- made the process more robust
- added support for mixing keys stored on yubikeys with keys from keystore files

Creation and setup of taf repositories enhancements

---

CHANGELOG.md
taf/git.py

If there are some problems with refs, git branch -r list return
a warning, regardless of if the branch exists or not. This means that
comparing the returned string with an empty string does not always
work

Branch exists fix

---

CHANGELOG.md
taf/auth_repo.py
taf/git.py

- Moved `safely_get_json` to the base git repository so that it can be used by any class which extends this git class - and not only authentication repositories
- A small `clone_or_pull` fix

Move safely_get_json and fix clone_or_pull

---

CHANGELOG.md
taf/auth_repo.py
taf/git.py
taf/log.py
taf/updater/updater.py

Lowered logging level in a few places. When an error occurs when executing a
git command and we neither want to reraise the error not use a customized log error message, such error is not that important. For example, a file does not exist at a revision. We often traverse through all commits and, e.g. try loading repositories.json. This file might not be available at the initial revision and that is not a problem.
Remove tuf logging when not needed
Small refactoring

Logging improvements

---

CHANGELOG.md
taf/auth_repo.py
taf/developer_tool.py
taf/git.py
taf/tools/targets/__init__.py
taf/tools/yubikey/__init__.py
taf/updater/updater.py

Implemented a command for exporting historical data of target repositories according to the authentication repository. It is possible to specify the first authentication repository commit to be taken into consideration when collecting historical data, as well as target repositories. If these parameters are not specified, history will be exported starting with the initial authentication commit and will include all target repositories.
To export history of two repositories, starting with a specific commit do the following:
`taf targets export_history auth_repo_path--repo namespace/repo1 --repo namespace/repo2` --commit sha`

Export historical targets data

---

CHANGELOG.md
taf/repository_tool.py

Raise a custom error instead of a `securesystemslib` error saying that a temp file does not exist

Raise a nicer error if an auth repository is not a valid TUF repository

---

CHANGELOG.md
taf/repositoriesdb.py
taf/repository_tool.py

- Set `only_load_targets` to True by default. It makes sense to ignore repositories specified in `repositories.json` with not corresponding target files.
- Updated the way of loading targets of a role given a commit. The updater was raising an error when case when the authentication repository had to be cloned due to not being able to read `targets.json`. Since this function was previously updated to use `repository_at_revision` context manager, we can rely on TUF's objects.

repositoriesdb fixes

---

CHANGELOG.md
taf/developer_tool.py
taf/repositoriesdb.py

When calling `export_history`:
`taf targets export_history law --repo namespace/law-html` 
it is checked if `namespace/law-html` is an actual target. If it is not, the command returns a warning message and is terminated without calling `sorted_commits_and_branches_per_repositories` which is slow on Windows.

When exporting history, check if the specified repo exists

---

CHANGELOG.md
taf/developer_tool.py
taf/tools/metadata/__init__.py

Added a command for adding new delegated targets roles.
New roles are specified using the same json input files which are used when creating a new repository, but it's not necessary
to list existing roles (unless these roles are delegated roles which are parents of other delegated roles)
This is an example of such json. It is assumed that parent of the two top roles (delegated_role1 and delegated_role2) is targets.
Parent of role1 is delegated_role2.
```
{
"roles":{
"delegated_role1":{
"paths":[
"dir1/*"
],
"number":1,
"threshold":1,
"scheme":"rsassa-pss-sha256",
"yubikey":true
},
"delegated_role2":{
"paths":[
"dir2/*"
],
"delegations":{
"role1":{
"paths":[
"test"
],
"yubikey":true
}
},
"scheme":"rsassa-pss-sha256",
"number":1,
"threshold":1,
"yubikey":true
}
},
"keystore":"keystore"
} …
```

Command for adding new delegated roles

---

CHANGELOG.md
setup.py

A function used by `yubikey-manager` was deprecated in newer `cryptography` releases. Until `yubikey-manager` is updated, it is necessary to use an older `cryptography` release

Pin cryptography version and bump version

---

CHANGELOG.md
taf/auth_repo.py
taf/exceptions.py
taf/git.py
taf/log.py
taf/repository_tool.py
taf/settings.py
taf/tests/test_updater.py
taf/tools/repo/__init__.py
taf/updater/handlers.py
taf/updater/updater.py

- Raise an error if there are additional commits newer than the last authenticated commit if the updater is called with the `check-authenticated` flag 
- A minor validation command fix
- Some improvements made to the updater's error messages
- Initial worktrees support . When merging commits, we need to check out branches which need to be updated. That cannot be done if they are checked out in a different worktree. So try to switch to that worktree and update the branch. Currently, there is no validation if that is possible or permissible. 
- Added support for specifying location of the conf directory
- Replaced authenticate-test-repo flag with an enum
- Added a function for disabling fie logging
[commit …

Various updater fixes and enhancements

---

CHANGELOG.md
taf/git.py
taf/repository_tool.py
taf/updater/updater.py

- Added a flag which makes it possible to only update and validate the repositories without checking out the last validated commit
- Fixed handling of additional commits on a branch
- A minor branch exists fix
- Compare current head commit according to the auth repo and top commit of target repo

Support for skipping automatic checkout and updater fixes

---

CHANGELOG.md
azure-pipelines.yml
taf/git.py
taf/tests/test_updater.py
taf/tools/yubikey/__init__.py
taf/updater/handlers.py
taf/updater/updater.py

- Remove commit checkout - this leaves a repository in detached commit state. Instead, checkout the latest branch. This makes sense because if a branch cannot contain unauthenticated commits, the validation should fail if there are additional commits. If it can contain such commits, there is a flag to raise an error if there are additional unauthenticated commits in the remote repository which are not available locally. That means that the user needs to pull manually and check the new commits, thus making sure that they look good.
- If top commit of the authentication repository is not the same as the `last_validated_commit`, validate the newer commits as if they were just pulled. Do the same if a target repository contains commits which are newer than the ones which correspond to the …

Remove checkout commit and validate commits newer than the last_validated_commit

---

CHANGELOG.md
taf/tests/test_updater.py
taf/tools/repo/__init__.py
taf/updater/updater.py

- Raise an error if a repository which should not contain additional commits does so
- Do not merge commits if update will later fail because there is a repo
with additional commits and error_if_unauthenticated flag is passed into
the updater
- Specify a list of repositories which shouldn't contain additional commits instead of just specifying a flag.
This makes it possible to only raise the exception if one of the repositories that can contain additional
commits according to repositories.json do so.
Can now invoke like this: 
`taf repo update https://github.com/oll-test-repos/cityofsanmateo-law  cityofsanmateo/law --default-branch master --error-if-unauthenticated-repos-list cityofsanmateo/law-xml`
[commit …

Error if unauthenticated fixes

---

CHANGELOG.md
setup.py

taf.tests module is not available in the wheel,
but the pytest11 entrypoint requires taf.tests, and
is always called by any pytest in any environment
that has taf installed. So any call to pytest will
always fail if taf wheel is installed.
By only conditionally adding pytest11 if taf.tests
exists, the entrypoint will only be available when
installed as source.

add pytest11 endpoint only if tests are available

---

CHANGELOG.md
taf/git.py
taf/updater/handlers.py
taf/updater/lifecycle_handlers.py
taf/updater/updater.py

Closes #22 
We've been recursively deleting the contents of current directory before running clone. This can be concerning depending on the file system path that's being deleted. Instead, simply raise an error if the repository that's being cloned into has file contents. This is how `git clone` operates aswell.
Also: fix print_data dump that leaves trailing `persistent.json` and `data` lying around on file system when running the updater.
Add a law repository, delete it's `.git` folder, and run the updater.

Clone should not always remove existing data

---

CHANGELOG.md
taf/exceptions.py
taf/tools/repo/__init__.py
taf/updater/updater.py

Closes #204 
Cross-post commit message:
* Based on https://github.com/openlawlibrary/taf/issues/204, we proposed the solution to remove the flag altogether.
Historically, this flag was used to specify repositories for which the
updater shouldn't perform the update if there are additional unauthenticated
commits.
* Now, we perform the update and the updater returns an update reponse.
Within that response is an `unauthenticated` commits dictionary (see
`schemas.py` for example [1]). We delegate the error handling to the end-user, instead of the framework.
* Remove --error-if-unauthenticated flag, and exceptions that were
raised.
[1] - law-xml updater response from [here](https://github.com/openlawlibrary/taf/blob/master/taf/tests/data/handler_inputs/valid/update/update.json)
```
"commits": …
```

Remove --error-if-unauthenticated

---

CHANGELOG.md
taf/updater/updater.py

Remove `no_checkout=True` argument for `clone` call, because we've already
validated targets calling clone, so we can safely checkout the default
branch now.

Clear clone `no_checkout=True`

---

CHANGELOG.md
taf/auth_repo.py
taf/git.py
taf/repositoriesdb.py

A security update made to git prevents execution of git commands if
the containing directory is owned by a different user. For example, if
repositories are owned by root and www-data tries to execute a git command.
It only affects commands executed using git cli - _git method of the git repo
class in TAF. pygit2 usage is not affected.
`allow_unsafe` flag can be set when instantiating the repositories allowing
the mentioned safety feature to be ignored. This is done by marking the
containing directory as safe. 

Add allow_unsafe flag as a response to a recent git security fix

---

CHANGELOG.md
taf/auth_repo.py
taf/git.py
taf/pygit.py
taf/tools/repo/__init__.py
taf/updater/handlers.py
taf/updater/updater.py
taf/utils.py

- Added timed_run decorator to updater calls which prints the total execution time
- Added profile flag to update cli. This makes it possible to easily generate .prof files.
- `targets_at_revision` performance improvement. If a new delegation is added and the new role contains targets, there
will have to be a metadata file. If no such changes are detected, we can be confident that there are no new roles. 

Performance and profiling

---

CHANGELOG.md
taf/git.py

* Sometimes we want to not include an additional merge commit, but only fast
forward a git merge.

Add `--ff-only` to merge commit

---

CHANGELOG.md
taf/tools/cli/taf.py

Add --version option to cli which prints taf's current version. Used cli's existing support for this feature

add --version option to cli which prints taf's current version

---

CHANGELOG.md
taf/validation.py

In `validate_branch` method `_unchanged_targets_metadata `, `updated_role` param is now converted to a list of `updated_roles` which is checked against `all_roles`

Convert `_unchanged_metadata`  updated_role to list

---

CHANGELOG.md
taf/auth_repo.py
taf/repositoriesdb.py
taf/tests/test_updater.py
taf/tools/repo/__init__.py
taf/updater/updater.py

Add support for the use case where some target repositories should be ignored. For example, it might be convenient to
only clone a subset of all target repositories and big repositories that are not needed. This is only recommended to be used
if library as a whole is getting validated regularly. When partially updating repositories, handlers are not called and
the `last_validated_commit` is not updated. This can be expanded at a later date so that we also save the information
regarding what was validated and updated, and what was not

Enable exclusion of certain target repositories from the update process

---

taf/exceptions.py
taf/git.py
taf/updater/handlers.py
taf/updater/updater.py

Raise `ValidationFailedError` when validation fails, `UpdateFiledError` whenever update fails
When validating repositories, settings `last_validated_commit` variables are updated
and if they are not reset afterwards, update might fail if run in the same process
following the update
As a git command for listing tags

Validation fixes and error handling, command for listing git tags

---

CHANGELOG.md
taf/tests/test_updater.py
taf/tools/repo/__init__.py
taf/updater/updater.py

Closes #217 
- Revert `taf repo update` click command back to old API by having `--clients-auth-path` as an argument. Now that argument is optional. `taf repo update` can be run by either specifying `<url>` and `<clients-auth-path>`, or with `<url>` and `--clients-library-dir`
- Do shutil.rmtree after unsuccessful `taf repo update` but not during validate. We don't want to clean up a law repository if validate fails.
- Clarify `info.json` error message

`--clients-auth-path` repo command improvements

---

CHANGELOG.md
taf/developer_tool.py
taf/repository_tool.py
taf/tools/metadata/__init__.py

Add check if metadata roles are expiring; condition-based automatic signing of snapshot and timestamp 

---

CHANGELOG.md
taf/updater/updater.py
taf/utils.py

Closes #264 
- `taf repo validate .` on a repository without specifying `--default-branch`

`taf repo validate` cleanup fix

---

CHANGELOG.md
taf/git.py

* If pygit.repo handler isn't instantiated, an exception is raised (and not caught) in other parts of `git.py` methods. For example, in `head_commit_sha()` there's a reference to pygit_repo, which will fail if repo handler wasn't properly instantiated. If handler is not instatiated, return None.
Minor fix to `pygit_repo` property in `git.py`

fix: update pygit_repo error handling

---

CHANGELOG.md
taf/git.py

The old implementation, before pygit2 could handle inputs such as HEAD - branch_name which is not actually a branch, but a reference. Add the same support to the new implementation and ensure backwards compatibility

fix: top_commit_of_branch extended to handle HEAD as branch name

---

.github/workflows/ci.yml

GitHub Actions is deprecating `v2` version by middle of next year
GitHub Actions is transitioning to `v3` from `v2`

refact: use `v3` in `actions/checkout@` version

---

CHANGELOG.md
setup.py
taf/developer_tool.py
taf/repository_tool.py
taf/tools/metadata/__init__.py

Cryptography was missing since we it's never installed by just relying on `oll-tuf`. 
Remove `timezone.utc` from datetime instances as upstream TUF has moved away from using `iso8601` module to make datetime objects.
Please see [current](https://github.com/openlawlibrary/tuf/blob/oll/tuf/repository_tool.py#L1404) vs [old](https://github.com/openlawlibrary/tuf/blob/24255c26b519efa4d466e35e9c2e50c4ed4ab002/tuf/repository_tool.py#L1281) `oll-tuf` 

Fix cryptography missing and remove `timezone.utc`

---

CHANGELOG.md
taf/git.py

`all_commits_since_commit` returned all commits on a branch or repository even if an invalid commit sha was provided. Validate current_commit and raise an error if commit is invalid.
Closes #277 

fix: Validate if provided commit exists in `all_commits_since_commit`

---

CHANGELOG.md
taf/git.py
taf/pygit.py

Closes #284 
Since transitioning to Python 3.10 and `pygit2>=1.*`  there were some breaking changes which then defaulted to us using git submodule. This caused a significant slowdown of updater.

performance: fix pygit2 breaking change

---

CHANGELOG.md
taf/git.py
taf/updater/updater.py

Instead of all_fetched_commits, all_commits_on_branch, which
was implemented using pygit2 can be called - as long as the
branch which is passed to it is a remote branch.
all_fetched_commits would return an empty list in some cases when
there were commits on the remote branch. all_commits_on_branch returned
the correct commits in those cases on the other hand.

Fetched commits bug

---

CHANGELOG.md
taf/repository_tool.py
taf/tools/repo/__init__.py
taf/utils.py

Instead of confirming that every path specified in `paths` attribute of `targets` metadata also exists in `repositories.json`, we really want to be getting the paths that exist in both `repositories.json` and targets metadata. By specifying `any` instead of `all`, we get the intersection between targets and repositories.json. On the other hand, by specifying `all` we're locking ourselves out of getting any paths at all.

fix: correctly retrieve `get_role_repositories`

---

CHANGELOG.md
taf/auth_repo.py
taf/updater/handlers.py
taf/updater/updater.py

1. `validation_auth_repo` should be an instance of `AuthenticationRepository`, not `GitRepository`.
2. Move loading `targets.json` metadata from updater to `is_test_repo` property
3. Change `_validate_authentication_repository` to check against the `is_test_repo` property.

fix: Use `is_test_repo` AuthRepository property in updater

---

CHANGELOG.md
setup.py
taf/repository_tool.py

This needs to be run before a TUF repositry is instantiated. However, it was causing issues with installation of TAF.
tuf.repository_lib.get_targets_metadata_fileinfo does not exist in older versions of TUF, so TUF had to be manually updated before TAF could be installed

fix: move _tuf_patches to repository lib

---

CHANGELOG.md
setup.py

Cryptography relies on pyOpenSSL, but is not automatically upgraded when Cryptography is updated. Since this dependency was pinned before in taf, we can safely pin again.

fix: pin pyOpenSSL

---

setup.py

In #200 attempted to conditionally add pytest11 only when tests were available, but forgot to remove pytest11 from the default set of entrypoints. This fixes that.

fix: remove pytest11 default entrypoint

---

CHANGELOG.md
taf/developer_tool.py

securesystemslib v0.25 uses a different interface to generate an rsa keypair with no password

fix: use `generate_and_write_unencrypted_rsa_keypair` for no provided password

---

taf/validation.py

During validation of branches, we compare if commits listed in target files are equal to commits of target repositories. This feature is similar to what the updater does, but validates content of branches that is yet to be merged into branches that the updater validates. If the target file does not exist and commit does, that should be an error, but we should raise a descriptive error instead of validation crashing because of a `GitError`

fix: raise InvalidBranchError if target file does not exist and commit does in branch validation

---

CHANGELOG.md
taf/developer_tool.py
taf/tools/metadata/__init__.py
taf/tools/targets/__init__.py

Added a command which updates target files corresponding to target repositories specified through the target type input parameter. Automatically sign and commit
`taf targets update-and-sign-targets law --target-type html --target-type xml --keystore ..\keystore-dev\keystore-dev`

feat: add a command for updating and signing targets of specified type

---

CHANGELOG.md
setup.py
taf/api/keystore.py
taf/api/metadata.py
taf/api/repository.py
taf/api/roles.py
taf/api/targets.py
taf/api/yubikey.py
taf/keys.py

- Added missing docstrings, adopting the newest format used in TUF
- Fixed create repository command following extensive refactoring
- Work on improving logging, see #27 

Apis docstirngs and improved logging, fix create repository

---

CHANGELOG.md
taf/api/targets.py
taf/tools/targets/__init__.py

Signing was not working without adding this flag

fix: add missing `write` flag to `taf targets sign`

---

CHANGELOG.md
taf/auth_repo.py

When finding all commits on branches based on target files, there was a check which skipped targets data in case
it remained the same between two consecutive authentication repo commits. However, this also skipped targets which
had the same commit, but different branches, causing validation failures.

fix: fix commits per repositories function when same target commits are on different branches

---

CHANGELOG.md
taf/tools/repo/__init__.py
taf/updater/updater.py

Closes #335 
When initially cloning the repo, url is still necessary, so `url` is now an option and not a required argument

Updater: automatically determined url if local repository exists

---

CHANGELOG.md
taf/git.py
taf/updater/updater.py

The problem with loading all repositories that were specified in `repositories.json`, even those that were removed is that a lot of the time the reason for removal is incorrect definition. For example, if there was a typo. At some point, we could implement something that could allow us to differentiate between invalid definitions and repositories that are no longer needed, but for now it makes sense to load only repositories specified in the newest version of `repositories.json`

fix: (updater) only load repositories defined in the newest version of repositories.json

---

docs/quickstart.md
docs/repo-creation-and-update-util.md
docs/setting-up-new-library.md
taf/api/metadata.py
taf/api/repository.py
taf/api/roles.py
taf/api/targets.py
taf/api/utils.py
taf/exceptions.py
taf/tools/dependencies/__init__.py
taf/tools/metadata/__init__.py
taf/tools/repo/__init__.py
taf/tools/roles/__init__.py
taf/tools/targets/__init__.py

- Standardize the way in which authentication repository's path is specified. Make it optional and set the default value to the current working directory. The option is now called `--path` across all commands.
- Check if working repository is clean before running repo, targets, metadata, roles and dependecies commands
- Added additional logging
- Update documentation following recent reworks
Closes #224 
Closes #27

CLI and docs improvements: standardize auth path parameter name, check if worktree is clean, update docs

---

CHANGELOG.md
taf/api/metadata.py
taf/api/repository.py
taf/api/roles.py
taf/api/targets.py
taf/git.py
taf/keys.py
taf/keystore.py
taf/tools/cli/__init__.py
taf/tools/dependencies/__init__.py
taf/tools/metadata/__init__.py
taf/tools/repo/__init__.py
taf/tools/roles/__init__.py
taf/tools/targets/__init__.py

When loading signing keys, we check if there is a keystore file, then if we can sign using a yubikey before eventually asking the user to manually enter the key (an option that a user might want to use if they want to store the private key in a different way, neither on their filesystem nor on a YubiKey). The problem with this is that in majority of the cases, a user actually wanted to use a keystore file, but provided an incorrect location and they do not want to copy/paste this key. At that point, we had to manually terminate the application. This PR adds a prompt which gives the user an option to say that they do not want to enter this key, in which case an error is raised. This error is caught and the information that the role's metadata could not be signed is printed.
Also added CLI …

Make it possible to abort signing if keys cannot be loaded, improve cli error handling

---

CHANGELOG.md
taf/api/roles.py
taf/api/targets.py
taf/api/yubikey.py
taf/auth_repo.py
taf/exceptions.py
taf/keys.py
taf/models/models.py
taf/tools/roles/__init__.py
taf/tools/yubikey/__init__.py

- List all keys of the specified role. If certs directory exists and contains certificates exported from YubiKeys, include additional information read from these certificates, like name or organization.
- Export its certificate from the inserted YubiKey - not tested yet
This PR includes code which was previously only in the TAF management application.
Closes #17 

List keys of roles and export certificate commands

---

CHANGELOG.md
taf/api/roles.py
taf/api/utils/__init__.py
taf/api/utils/_git.py
taf/api/utils/_metadata.py
taf/keys.py
taf/models/types.py
taf/yubikey.py

When loading signing keys, we want to first try reading from keystore files, then from the inserted Yubikey, before asking the user to do anything. The problem was that the check if key was already read from a YubiKey was not properly implemented, so the same key was getting read twice. Also tried to improve the overall user experience when loading keys.
Found issues with creating a repository in case when old `yubikey` flag was used to specify that a role's metadata files should be signed using YubiKeys.

Fix loading of keys and  create repo when old yubikey flag is used

---

CHANGELOG.md
taf/api/utils/_roles.py
taf/keys.py
taf/tests/test_updater/test_repo_update/test_updater.py
taf/updater/updater_pipeline.py

- Made it possible to run the updater without installing yubikey manager
- Fixed a `GitError` impor
- Fixed a failing tests following update of the imports. The behavior of this test is now the same as before the updater rework

Fix imports, do not require installation of ykman in order to run the updater

---

docs/repo-creation-and-update-util.md
docs/updater/update_process.md
taf/exceptions.py
taf/tests/test_updater/test_repo_update/test_updater.py
taf/tools/repo/__init__.py
taf/updater/handlers.py
taf/updater/types/update.py
taf/updater/updater.py
taf/updater/updater_pipeline.py
taf/utils.py

Separated clone and update commands: This separation mirrors Git, where cloning and pulling are separate operations.
The clone command is used for the initial setup of repositories.
If the `--path` option is not provided during cloning, the updater automatically reads from `protected/info.json` to determine the repository's location. `library-dir`, if nor provided, is set to the current directory and the namespace and name read from `info.json` are appended to this path to determine authentication repository's location.
The update command is designed to pull changes into an already cloned repository.
When updating, the URL of the repository is automatically determined and is not expected to be specified.
If the --path option is not provided, the command defaults to using the current …

Separate clone and update commands and read repository name from info.json when cloning

---

CHANGELOG.md
taf/exceptions.py
taf/tests/test_updater/test_repo_update/test_updater.py
taf/updater/updater_pipeline.py

- If the authentication repository contains an invalid commit, it will be partially updated, up until the last valid commit
- If multiple errors occur, print them all
- Do not merge unauthenticated commits which are newer than the last authenticated commit if a repository can contain unauthenticated commits
- Only clone repositories if target files exists
- Print additional commits of repositories which allow unauthenticated commits at the end of the update process
- Revert merged commit if invalid
Closes #281 

Partially update authentication repository in case it cannot be fully validated and clone and unauthenticated commits fixes

---

CHANGELOG.md
taf/repositoriesdb.py
taf/tests/conftest.py
taf/tests/init_data/dependencies.json
taf/tests/init_data/keys.json
taf/tests/test_updater/test_repo_update/conftest.py
taf/tests/test_updater/test_repo_update/test_updater.py
taf/updater/updater_pipeline.py

This test programmatically sets up repositories instead of adding a previously created repository with .git folder renamed to git
Also fixed a minor bug where update status was incorrectly being set in case when a repository with only one commit is cloned

Add test for updating a repositories which references other authentication repositories

---

CHANGELOG.md
taf/git.py
taf/repositoriesdb.py
taf/updater/updater_pipeline.py

- When only validating repositories, validation would fail if there were no local branches. Commits can still be listed given a remote branch. Local branches do not exist after a repository is cloned unless it is checked out.
- Fix `GitError` exception instantiation 
- Update `find_first_branch_matching_pattern` return - only return name of the found branch and not all branches whose name did not match the pattern

Validation fix, GitError exception instantiation fixes

---

CHANGELOG.md
taf/tests/test_updater/test_repo_update/test_updater.py
taf/updater/handlers.py
taf/updater/updater.py
taf/updater/updater_pipeline.py

TUF updater does not always check the validity of all metadata files
if timestamp is not updated, the updater will determine that a new version
of the snapshot file does not need to be downloaded and it will not be validated
during the update process, the metadata files that TUF updater downloads is stored
in a separate folder within the temp directory
For each commit, check if the metadata files inside that directory are the same
as the ones in the auth repository's metadata folder at that revision
Closes #385 

Check if metadata files at revision match those downloaded by TUF updater

---

CHANGELOG.md
taf/tools/roles/__init__.py

Invocation:
`taf roles add-role-paths rdf --delegated-path missing-path-1 --delegated-path missin-path-2 --keystore keystore-path`

Add a command for adding delegated paths to a role

---

CHANGELOG.md
taf/exceptions.py
taf/git.py
taf/tests/test_updater/test_repo_update/test_updater.py
taf/updater/updater.py
taf/updater/updater_pipeline.py

- Fix logic for determining if a commits should be merged
- Remove checkout option since we were always checking out the branch. After cloning, if a branch is not checked out, the index will end up being dirty, showing that the repository's content was removed. We could potentially avoid this checkout by checking if the repository was cloned and then make sure that nothing else fails without it. This can be done later.
- Only show "Merging commits" message  if commits are actually getting merged, and not always before and after that function is called
Closes #395

Improve merge commits

---

CHANGELOG.md
taf/git.py
taf/tests/test_git/conftest.py
taf/tests/test_git/test_git.py
taf/updater/updater_pipeline.py
taf/utils.py

Do not clone target repositories directly to their permanent location. Clone to temp first, just like when working with authentication repositories. If a repository is already on disk, copy that to temp, update temp, then fetch changes from temp if valid.
Note: This PR does not address the issue of not cloning when running validation. That can be done in a separate PR
Closes #408 

Clone target repositories to temp

---

CHANGELOG.md
taf/git.py
taf/tests/test_git/conftest.py
taf/tests/test_git/test_git.py

This bug was introduced by unreleased changes, which made it impossible to run update after cloning in cases where
there are authenticated commits that do not get merged. The check needs to be more complex than just checking if
top commits are the same.
Fix #414

fix is_branch_with_unpushed_commits

---

CHANGELOG.md
taf/git.py
taf/updater/updater_pipeline.py

The idea is for the update process to fail early if the auth repo or one of the existing target repositories is not clean (index is dirty or if there are unpushed commits). After updating the authentication repository, we can check other branches.
Closes #390

Check if repositories are clean before running the updater

---

CHANGELOG.md
taf/git.py
taf/updater/updater_pipeline.py

If a commit is on the remote tracking branch and the local branch is not updated, it will not be fetched when fetching from that temp repo. This resulted in an error during the merge commits step.
Discovered this issue while running integration tests. That testing framework is a lot different than this one. We should keep this in mind when we start reworking this testing framework.

fix: update temp local branch before fetching from it

---

CHANGELOG.md
taf/git.py

`self.urls` is not deterministic between OSs, so on Windows it returns remote repositories last, and on macOS it returns them first. This commit makes it so we don't rely on `self.urls`.
Also, since the for loop doesn't access or use url variable, I've removed it.
Closes: #372

fix: use provided url or get remote url

---

CHANGELOG.md
taf/api/targets.py

Role paths should not be added if the signing role is the top-level targets role

fix: fix add_target_repo when signing role is the top-level targets role

---

taf/tools/dependencies/__init__.py

Removing redundant CLI print line to fix the double print of keystore option when "taf dependencies add --help" is used.
Fixes #428
Issue: "taf dependencies add --help" lists "--keystore" twice
Changes to address the Issue: Removed redundant print lines in "taf dependencies add --help".

Fix for redundant printing of CLI help options

---

CHANGELOG.md
taf/api/keystore.py
taf/api/roles.py
taf/keys.py

A feature that we rarely use, but still want to support is printing keys to the command line instead of storing them to the keystore files. This enables the users to copy them to a secure key manager. 
Fix #433

Fix generation of keys when they should be printed to the command line

---

taf/api/targets.py
taf/tools/targets/__init__.py

fixes: #430
Updated the order of adding repository based on target_path if provided, else based on target_name if target_path is empty. Completely making target_name mandatory might break the functionality of updater based repository additions, so did not completely remove the target_path based repository addition.
Updated the `--target-name` option as required in the CLI. However, I have maintained the default assignment as `None` because the API function relies on `None` to determine if the `target-name` was provided or not.

Fix: Update to repository addition order

---

CHANGELOG.md
taf/repositoriesdb.py

Always load the latest version of mirrors.json. It does not ever make sense to attempt to download a repository from a URL which updated. This also ensures that the update can succeed if we there are commits where repositories.json existed, but mirrors was added later
Also removed a function that is no longer used

Always load latest mirrors.json

---

CHANGELOG.md
taf/yubikey.py

The error was caused by wrong indentation, which meant that the function that stores the key on a yubikey was only being called in some cases
Fix #369

fix: fix setup yubikey

---

CHANGELOG.md
taf/updater/updater.py
taf/yubikey.py

Utilized getpass() to hide the plaintext when prompted to "insert {key_name} YubiKey and press ENTER." Fix #399.

fix: hide plaintext yuibkey input

---

CHANGELOG.md
taf/api/targets.py
taf/exceptions.py
taf/git.py
taf/pygit.py
taf/tests/test_git/test_git.py
taf/tests/test_repository/test_repository.py
taf/updater/updater_pipeline.py

Implement `is_git_repository` without using `pygit_repository` in order to avoid a circular invocation

is_git_repository rework and fix failing test

---

CHANGELOG.md
taf/api/conf.py
taf/api/roles.py
taf/api/yubikey.py
taf/keys.py
taf/tools/metadata/__init__.py
taf/tools/yubikey/__init__.py
taf/yubikey.py

Remove 2048-bit restriction for key sizes. See #446

feat: remove 2048-bit restriction for yubikey sizes

---

CHANGELOG.md
taf/api/targets.py
taf/api/utils/_roles.py

If public keys are specified in the keys-description, these verification keys are added without corresponding signing keys. TUF registers these key IDs as previous key IDs. This means that signing will fail unless one of the signing keys matches one of the public keys (we must have tested this with a YubiKey containing such a key).

Fix setup role

---

taf/tests/test_updater/update_utils.py
taf/tools/repo/__init__.py
taf/updater/handlers.py
taf/updater/updater.py
taf/updater/updater_pipeline.py

Fixes NILL when running `taf repo clone https://github.com/oll-test-repos/narf-nill-law.git` and some of the target repos have ssh instead of https urls.

fix: use mirrors.json urls when cloning dependencies

---

CHANGELOG.md
taf/api/conf.py
taf/api/dependencies.py
taf/api/keystore.py
taf/api/repository.py
taf/api/roles.py
taf/api/targets.py
taf/api/utils/_conf.py
taf/api/utils/_git.py
taf/api/utils/_metadata.py
taf/api/utils/_roles.py
taf/auth_repo.py
taf/exceptions.py
taf/git.py
taf/keys.py
taf/models/types.py
taf/repository_tool.py
taf/repository_utils.py
taf/tests/test_api/test_roles.py
taf/tools/cli/__init__.py
taf/tools/dependencies/__init__.py
taf/tools/keystore/__init__.py
taf/tools/metadata/__init__.py
taf/tools/repo/__init__.py
taf/tools/roles/__init__.py
taf/tools/targets/__init__.py
taf/updater/updater_pipeline.py
taf/yubikey.py

Contains a number of fixes and usability improvements, mostly related to some recent work (like updates made to logging, creation of a configuration directory, automatically finding an authentication repository), as well as some create repo fixes and a couple of new features. 
Adds a function for exporting `keys-description.json` based on the repository's current state. This is initial work towards storing this file in the repo's configuration directory and potentially using it to make operations like adding new roles or updating current ones easier.
Also contains work on handling more edge cases, catching more errors and cleaning up a repository after an error occurs.
Simplified two CLI commands by allowing specification of a custom file containing additional data. Determined that …

Usability improvements

---

CHANGELOG.md
setup.py
taf/api/yubikey.py
taf/repository_tool.py
taf/tools/yubikey/yubikey_utils.py
taf/yubikey.py

We do not currently, and have never needed to pass a public key pem to the piv context manager.
The code that is invoked if this pem is passed does not work, but the general idea is also not robust enough (see comments in #515).
Since we are not using this, I think that we should just remove this code. We'll implement it if a need for it arises.
Also found and fixed a minor `setup_test_yubikey` issue
Closes #515 

Remove unused optional parameter from _yk_piv_ctrl

---

CHANGELOG.md
taf/git.py
taf/tests/test_git/conftest.py
taf/tests/test_git/test_git.py

Added tests for the functionalities mentioned in issue #563
The behavior described in the issue description is not a bug, but was modified recently.
When resetting commits, remote tracking branches are updated too by default. This was
implemented as not doing so cause some nasty updater bugs.
Added a flag that can prevent that update, if it is not needed and expected in other use cases.
Also, `get_last_remote_commit` returns the commit of the remote repository, while `top_commit_of_remote_branch`
returns the top commit of the specified remote tracking branch. I updated the `top_commit_of_remote_branch` method's
docstring.  
Closes #563

Add tests for get last remote commit and reset to commit

---

CHANGELOG.md
taf/auth_repo.py
taf/updater/updater.py
taf/updater/updater_pipeline.py

This PR contains 4 simple fixes:
- After running a command which pushes to the auth repo, we update the last validated commit. However, since we only validated commits that are on the default branch, last validated commit should only be updated when pushing to this branch
- Similarly, when traversing a repo's commit history, only traverse the default branch's history, even if a different branch is currently checked out.
- Replaced an outdated check if a repo is a test repo
- Determining from which commit the update of target repos should start was incorrect in cases when all target repositories were updated up to the same auth commit, but the auth repo was updated in the meantime. When some target repositories are excluded from the update, their last validated commits will be different …

Fix: Fix setting last updated commit when pushing and update when only auth repo updated

---

CHANGELOG.md
setup.py
taf/resources/pre-push
taf/utils.py

- Run validation with --no-deps when pushing
- Always copy the  current pre-push hook
- Release 0.33.1

fix: run validation with --no-deps when pushing

---

taf/git.py

Sometimes we don't want to run pre-push hook validations when calling out to git push from our programs. To avoid running any git hooks, we bypass with `--no-verify`.

feat: add `no_verify` to methods that push

---

CHANGELOG.md
taf/api/api_workflow.py
taf/api/dependencies.py
taf/api/metadata.py
taf/api/roles.py
taf/api/targets.py
taf/api/utils/_conf.py
taf/api/utils/_git.py
taf/api/yubikey.py
taf/keys.py
taf/messages.py
taf/tests/test_api/roles/api/test_roles.py
taf/tests/tuf/test_query_repo/test_query_repo.py
taf/tools/cli/__init__.py
taf/tools/dependencies/__init__.py
taf/tools/metadata/__init__.py
taf/tools/roles/__init__.py
taf/tools/targets/__init__.py
taf/tuf/repository.py
taf/utils.py
taf/yubikey/yubikey.py

Implemented a command for adding/updating key names. The input can be the whole keys-description json, or just the "yubikeys" part of it. Added this input to all other commits that sign metadata files. Names of keys are read from these files if present. This can be used in case a repository was created before specifying key names was possible. Such repositories can also be updated using the new add key names command.
The key_management decorator is designed to handle loading signing keys within Click commands. The roles parameter defines a static list of TUF roles that require loaded signers. The roles_fn parameter allows dynamically determining roles based on user-provided PINs or other conditions. If none of them is provided, roles are determined based on the inserted YubiKeys. Captures …

Add key names and decorator

---

CHANGELOG.md
taf/keys.py
taf/log.py
taf/settings.py
taf/yubikey/yubikey.py

- Add a bunch of yubikey logging statements
- Add `taf-debug.log` log that stores our debug log statements.
- Since taf-debug.log grows relatively quickly in size, add logrotation with a file size limit and a retention rate

feat: add yubikey debug logs; introduce `taf-debug.log` and log rotation

---

CONTRIBUTING.md

This PR clarifies how contributions are handled license-wise. I don't think it's strictly necessary to have this added, but based on discussions we've had this may be handy to iterate on.
I'm therefore opening this PR to have an item for others to take a look at. We should be careful on the wording here and others more qualified than me should have a look of course.
On the gittuf project, we mandate the use of the [DCO](https://developercertificate.org/) [signoff](https://wiki.linuxfoundation.org/dco) to handle licensing, but TAF may likely have a different policy.

docs: Add licensing blurb to contribtuting docs

---

CHANGELOG.md
setup.py

Issues come up when installing taf without smart card packages installed on ubuntu machine. To sort out, we pin back pyscard in yubikey manager

fix: pin pyscard back in yubikey extras; release v0.35.3

---

CHANGELOG.md
setup.py
taf/api/targets.py
taf/utils.py

Targets files are already unix-style normalized. However, hash compare is flaky on Windows. This is because files that were previously touched by unix are now touched by windows and the hash compare becomes incorrect. To resolve, normalize content before compare

fix: normalize targets file contents prior hashing

---

.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGELOG.md
setup.py
taf/git.py
taf/log.py
taf/tuf/keys.py

Sometimes these functions get called twice and raise a `KeyError`. We now expect it and pass

fix: pass on `KeyError` when disabling logging
